GET http://localhost:8080/order?id=5

###

POST http://localhost:8080/order
Content-Type: application/json

{
  "id":5,
  "date":"23:11:2023 06:44:28",
  "cost":55.0,
  "products":[
    {
      "id":5,
      "name":"Car",
      "cost":50.0
    },
    {
      "id":6,
      "name":"Print",
      "cost":5.0
    }]
}
